name: TEST zip

#Trigger
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
     
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE     
 
    - name: See curent dir
      run: dir    
    
    - name: 'Zip files'
      run: 7z a -tzip D:\\a\\RemNamer\\RemNamer\\remNamer\\release-artifact.zip D:\a\RemNamer\RemNamer\remNamer
      continue-on-error: true
        
    - run: dir D:\a\RemNamer\RemNamer\remNamer\
